name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql
          coverage: none
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
      - name: Wait for MySQL
        run: sleep 15
      - name: Create Database
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:schema:update --force
      - name: Run Tests
        run: php bin/phpunit

  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql
          coverage: none
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

  analyze:
    name: Analyze 🔎
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql
          coverage: none
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
      - name: Run PHP Insights
        run: php vendor/bin/phpinsights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90 --ansi --format=github-action
      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run